include:
  - project: "iam/automation/templates/ci_cd-pipelines"
    file: "/.gitlab-ci-docker-build-publish.yml"

variables:
  CI_PROJECT_NAME: $CI_PROJECT_NAME
  DISABLE_GITLEAKS: "true"
  DOCKER_BUILD_ARGS: "--build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL --build-arg VITE_API_KEY=$VITE_API_KEY --build-arg VITE_CLIENT_ID=$VITE_CLIENT_ID --build-arg VITE_TENANT_ID=$VITE_TENANT_ID"

before_script:
  - echo "OSUSER=$OSUSER" > .env
  - echo "OSPASSWORD=$OSPASSWORD" >> .env
  - printenv | grep -E '^(VITE_)' >> .env || true
  - cat .env
