services:
  tts_frontend:
    image: "${HARBOR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
    ports:
      - "4457:80"
    restart: unless-stopped
    networks:
      - frontend-network
    mem_limit: 4g
    cpus: 0.5
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_CLIENT_ID=${VITE_CLIENT_ID}
      - VITE_TENANT_ID=${VITE_TENANT_ID}

networks:
  frontend-network:
    external: true
    name: app-network


