services:
  tts_frontend:
    image: "${HARBOR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
    ports:
      - "4457:4457"
    restart: unless-stopped
    networks:
      - small_apps
    mem_limit: 4g
    cpus: 0.5

networks:
  small_apps:
    name: small_apps

