services:
  tts_frontend:
    image: "${HARBOR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
    ports:
      - "4457:80"
    restart: unless-stopped
    networks:
      - frontend-network
    mem_limit: 4g
    cpus: 0.5

networks:
  frontend-network:
    external: true
    name: small_apps

